apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xsmoleniak/ambulance-ufe
  newName: xsmoleniak/ambulance-ufe
  newTag: 1.0.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: xsmoleniak/disease-monitor
  newName: xsmoleniak/disease-monitor
  newTag: 1.0.1