kind: Service
apiVersion: v1
metadata:
  name: ss-disease-monitor-openapi-ui
spec:
  selector:
    pod: ss-disease-monitor-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081