apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-disease-monitor-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /ss-disease-monitor-openapi
            - name: BASE_URL
              value: /ss-disease-monitor-openapi-ui