apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ss-disease-monitor-ufe-content
spec:
  microFrontend: ss-disease-monitor-ufe
  element: ss-disease-monitor-app
  attributes:
    - name: base-path
      value: /ss-disease-monitor/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ss-disease(.*)?$"