apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ss-disease-monitor-ufe-content
spec:
  microFrontend: ss-disease-monitor-ufe
  element: ss-disease-monitor-app
  attributes:
    - name: base-path
      value: /ss-disease-monitor/
    - name: region-id
      value: svk
    - name: api-base
      value: /ss-disease-monitor-api
    - name: image-path
      value: /fea/polyfea/proxy/wac-hospital/ss-disease-monitor-ufe/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ss-disease(.*)?$"