apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ss-disease-monitor-ufe-link
spec:
  microFrontend: polyfea-md-shell # referencia na microfrontend, z ktorého sa načíta element
  element: polyfea-md-app # element, ktorý bude vložený na stránku
  attributes: # atribúty elementu polyfea-md-app
    - name: headline
      value: Vizualizácia výskytu chorôb ss
    - name: short-headline
      value: Vizualizácia výskytu chorôb ss
    - name: supporting-text
      value: |
        Spravuje a vizualizuje prípady chorôb v geografickom priestore
    - name: material-icon
      value: pin_drop
    - name: href # presmerovanie po kliknutí na element polyfea-md-app
      value: ./ss-disease-monitor
  priority: 10
  displayRules: # pravidlá, kde sa má element vložiť v obálke
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content