apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xsmoleniak/ambulance-ufe
  newName: xsmoleniak/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20250318.1231 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: xsmoleniak/ambulance-wl-webapi
  newName: xsmoleniak/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20250409.1038 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: xsmoleniak/disease-monitor
  newName: xsmoleniak/disease-monitor # {"$imagepolicy":  "wac-hospital:disease-monitor-ufe:name"}
  newTag: main.20250529.2204 # {"$imagepolicy": "wac-hospital:disease-monitor-ufe:tag"}
- name: xsmoleniak/disease-monitor-webapi
  newName: xsmoleniak/disease-monitor-webapi # {"$imagepolicy":  "wac-hospital:disease-monitor-webapi:name"}
  newTag: main.20250529.1748 # {"$imagepolicy": "wac-hospital:disease-monitor-webapi:tag"}
